version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bikes
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: